from fpdf import FPDF

def safe_text(text):
    if not isinstance(text, str):
        text = str(text)
    return text.encode('latin-1', errors='ignore').decode('latin-1')

class PDFReport(FPDF):
    def header(self):
        self.set_font("Arial", 'B', 14)
        self.cell(0, 10, "TruCred: Verified Financial Report", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by TruCred", align="C")

def generate_pdf(user_data, score, grade,
                 rent_status="Not uploaded",
                 mobile_status="Not uploaded",
                 utility_status="Not uploaded",
                 output_path="financial_report.pdf"):

    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    pdf.cell(0, 10, f"Name: {safe_text(user_data['name'])}", ln=True)
    pdf.cell(0, 10, f"Email: {safe_text(user_data['email'])}", ln=True)
    pdf.cell(0, 10, f"Phone: {safe_text(user_data['phone'])}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"Trust Score: {safe_text(score)} / 100", ln=True)
    pdf.cell(0, 10, f"Grade: {safe_text(grade)}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Timely EMI/Recurring Payments (Months): {user_data['rent_paid_on_time']}", ln=True)
    pdf.cell(0, 10, f"Mobile Recharge Regular: {safe_text(user_data['mobile_recharge'])}", ln=True)
    pdf.cell(0, 10, f"Utility Bill in Name: {safe_text(user_data['utility_bill'])}", ln=True)
    pdf.cell(0, 10, f"UPI File Uploaded: {safe_text(user_data['upi_uploaded'])}", ln=True)
    pdf.cell(0, 10, f"Spending Consistent: {safe_text(user_data['spending_consistent'])}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Reference Check", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"{safe_text(user_data['reference_name'])} ({safe_text(user_data['reference_relationship'])})", ln=True)
    pdf.cell(0, 10, f"Feedback: {safe_text(user_data['reference_feedback'].capitalize())}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Document Verification Status", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Recurring Payment Proof: {safe_text(rent_status)}", ln=True)
    pdf.cell(0, 10, f"Mobile Recharge Proof: {safe_text(mobile_status)}", ln=True)
    pdf.cell(0, 10, f"Utility Bill Proof: {safe_text(utility_status)}", ln=True)

    pdf.output(output_path)
    return output_path
