from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        self.set_font("Arial", 'B', 14)
        self.cell(0, 10, "TruCred: Verified Financial Report", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by TruCred", align="C")

def generate_pdf(user_data, score, grade, output_path="financial_report.pdf"):
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    pdf.cell(0, 10, f"Name: {user_data['name']}", ln=True)
    pdf.cell(0, 10, f"Email: {user_data['email']}", ln=True)
    pdf.cell(0, 10, f"Phone: {user_data['phone']}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"📊 Trust Score: {score} / 100", ln=True)
    pdf.cell(0, 10, f"🎓 Grade: {grade}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, "🏠 Rent paid on time (months): " + str(user_data["rent_paid_on_time"]), ln=True)
    pdf.cell(0, 10, "📶 Mobile recharge consistent: " + user_data["mobile_recharge"], ln=True)
    pdf.cell(0, 10, "💡 Utility bill provided: " + user_data["utility_bill"], ln=True)
    pdf.cell(0, 10, "📂 UPI uploaded: " + str(user_data["upi_uploaded"]), ln=True)
    pdf.cell(0, 10, "📈 UPI spending consistent: " + str(user_data["spending_consistent"]), ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "👤 Reference", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"{user_data['reference_name']} ({user_data['reference_relationship']})", ln=True)
    pdf.cell(0, 10, f"Feedback: {user_data['reference_feedback'].capitalize()}", ln=True)

    pdf.output(output_path)
    return output_path
